#FROM node:15.14-alpine3.10

FROM node:alpine

#RUN apk add --no-cache nodejs npm

WORKDIR '/app'

#COPY . .
COPY package.json .


# Create and attribute permission in cache folder
RUN mkdir -p /app/node_modules/.cache && \
    chown root:root -R /app/node_modules/.cache && \
    chmod 777 -R /app/node_modules/.cache


RUN npm install

#COPY . .

#EXPOSE 3000

CMD ["npm", "run", "start"]
