#FROM node:15.14-alpine3.10 

FROM node:alpine

#RUN apk add --no-cache nodejs npm

WORKDIR '/app'

#COPY . .
COPY package.json .

#RUN echo "nameserver 8.8.8.8 > /etc/resolv.conf"
#RUN npm install chokidar

RUN npm install

#COPY . .

#EXPOSE 3000

CMD ["npm", "run", "start"]
